# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimg',
            name='img',
            field=models.ImageField(upload_to='project_img/'),
        ),
    ]
